sudo: false
language: objective-c
osx_image: xcode9.4.1

script:
- swift package generate-xcodeproj --enable-code-coverage
- xcodebuild -project Regex.xcodeproj -scheme Regex-Package test

after_success:
- bash <(curl -s https://codecov.io/bash)
